"""empty message

Revision ID: 06517eada72e
Revises: 4ee0737df6de
Create Date: 2016-09-17 11:14:04.839783

"""

# revision identifiers, used by Alembic.
revision = '06517eada72e'
down_revision = '4ee0737df6de'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ultimo_envio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('resumo', sa.String(), nullable=False),
    sa.Column('corpo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticias')
    op.drop_table('newsletters')
    ### end Alembic commands ###
