"""empty message

Revision ID: 0fd7e4abed38
Revises: bb2a34ab0c01
Create Date: 2016-09-17 22:28:35.649866

"""

# revision identifiers, used by Alembic.
revision = '0fd7e4abed38'
down_revision = 'bb2a34ab0c01'

from alembic import op
import app
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('imagens_url', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias', 'imagens_url')
    ### end Alembic commands ###
