"""empty message

Revision ID: 12353e7e9d34
Revises: df7c9e698ce1
Create Date: 2016-03-03 23:57:52.267718

"""

# revision identifiers, used by Alembic.
revision = '12353e7e9d34'
down_revision = 'f8b110875ac9'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provas_inscricoes',
    sa.Column('prova_id', sa.Integer(), nullable=True),
    sa.Column('inscricao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inscricao_id'], ['inscricoes.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.PrimaryKeyConstraint('prova_id', 'inscricao_id')
    )
    op.add_column(u'atletas', sa.Column('senha_hash', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'atletas', ['email'])
    op.add_column(u'inscricoes', sa.Column('tipo_afiliacao', app.database.AfiliacaoTipo(), nullable=True))
    op.drop_constraint(u'inscricoes_prova_id_fkey', 'inscricoes', type_='foreignkey')
    op.drop_column(u'inscricoes', 'prova_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'inscricoes', sa.Column('prova_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'inscricoes_prova_id_fkey', 'inscricoes', 'provas', ['prova_id'], ['id'])
    op.drop_column(u'inscricoes', 'tipo_afiliacao')
    op.drop_constraint(None, 'atletas', type_='unique')
    op.drop_column(u'atletas', 'senha_hash')
    op.drop_table('provas_inscricoes')
    ### end Alembic commands ###
