"""empty message

Revision ID: 2bdf34717b73
Revises: b5d1066a61cd
Create Date: 2016-03-02 19:03:46.814353

"""

# revision identifiers, used by Alembic.
revision = '2bdf34717b73'
down_revision = 'b5d1066a61cd'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provas', sa.Column('evento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'provas', 'eventos', ['evento_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provas', type_='foreignkey')
    op.drop_column('provas', 'evento_id')
    ### end Alembic commands ###
