"""empty message

Revision ID: 445667ce6268
Revises: 955f4593a961
Create Date: 2016-03-02 20:00:54.731791

"""

# revision identifiers, used by Alembic.
revision = '445667ce6268'
down_revision = '955f4593a961'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('data_fim', sa.Date(), nullable=True))
    op.add_column('eventos', sa.Column('data_inicio', sa.Date(), nullable=True))
    op.drop_column('eventos', 'href_link')
    op.drop_column('eventos', 'fundo')
    op.drop_column('eventos', 'nome_link')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('nome_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('fundo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('eventos', sa.Column('href_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('eventos', 'data_inicio')
    op.drop_column('eventos', 'data_fim')
    ### end Alembic commands ###
