"""empty message

Revision ID: 455980e4b944
Revises: fd6e26bc74e3
Create Date: 2016-03-01 17:39:23.587508

"""

# revision identifiers, used by Alembic.
revision = '455980e4b944'
down_revision = 'fd6e26bc74e3'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onde_remar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('modalidade', app.database.ModalidadeTipo(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onde_remar')
    ### end Alembic commands ###
