"""empty message

Revision ID: 5e873c9ec136
Revises: 12353e7e9d34
Create Date: 2016-03-07 23:53:45.023182

"""

# revision identifiers, used by Alembic.
revision = '5e873c9ec136'
down_revision = '12353e7e9d34'

from alembic import op
import app
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('pontuacao', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'pontuacao')
    ### end Alembic commands ###
