"""empty message

Revision ID: 6506ed199f9b
Revises: 9299fd9d6cfd
Create Date: 2016-03-03 11:14:42.464166

"""

# revision identifiers, used by Alembic.
revision = '6506ed199f9b'
down_revision = '9299fd9d6cfd'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provas', sa.Column('revezamento', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provas', 'revezamento')
    ### end Alembic commands ###
