"""empty message

Revision ID: 6d8e9e4138bf
Revises: 445667ce6268
Create Date: 2016-03-03 10:36:03.205829

"""

# revision identifiers, used by Alembic.
revision = '6d8e9e4138bf'
down_revision = '445667ce6268'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provas', sa.Column('data_inicio', sa.DateTime(), nullable=True))
    op.add_column('provas', sa.Column('tempo_execucao', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provas', 'tempo_execucao')
    op.drop_column('provas', 'data_inicio')
    ### end Alembic commands ###
