"""empty message

Revision ID: 70d0db914e82
Revises: c2d74790a74e
Create Date: 2016-03-14 20:55:08.968638

"""

# revision identifiers, used by Alembic.
revision = '70d0db914e82'
down_revision = 'c2d74790a74e'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscricoes', sa.Column('evento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inscricoes', 'eventos', ['evento_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inscricoes', type_='foreignkey')
    op.drop_column('inscricoes', 'evento_id')
    ### end Alembic commands ###
