"""empty message

Revision ID: 8d8b79d14d9f
Revises: 2c24a29be2b8
Create Date: 2016-04-02 02:24:06.871963

"""

# revision identifiers, used by Alembic.
revision = '8d8b79d14d9f'
down_revision = '2c24a29be2b8'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.Column('tempo', sa.String(length=20), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    ### end Alembic commands ###
