"""empty message

Revision ID: 906c5a1888e0
Revises: ca31a5843986
Create Date: 2016-09-17 14:26:41.347523

"""

# revision identifiers, used by Alembic.
revision = '906c5a1888e0'
down_revision = 'ca31a5843986'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('data_publicacao', sa.DateTime(), nullable=True))
    op.add_column('noticias', sa.Column('publicado', sa.Boolean(), nullable=True))
    op.add_column('noticias', sa.Column('titulo', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias', 'titulo')
    op.drop_column('noticias', 'publicado')
    op.drop_column('noticias', 'data_publicacao')
    ### end Alembic commands ###
