"""empty message

Revision ID: 95e81423cf0c
Revises: e554f67657d1
Create Date: 2016-09-17 14:19:24.962339

"""

# revision identifiers, used by Alembic.
revision = '95e81423cf0c'
down_revision = 'e554f67657d1'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('corpo_novo', sa.Text(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias', 'corpo_novo')
    ### end Alembic commands ###
