"""empty message

Revision ID: 9f0fa98ec79d
Revises: 5e873c9ec136
Create Date: 2016-03-08 00:15:10.934364

"""

# revision identifiers, used by Alembic.
revision = '9f0fa98ec79d'
down_revision = '5e873c9ec136'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('resumo', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'resumo')
    ### end Alembic commands ###
