"""empty message

Revision ID: b5d1066a61cd
Revises: 455980e4b944
Create Date: 2016-03-01 23:05:13.755064

"""

# revision identifiers, used by Alembic.
revision = 'b5d1066a61cd'
down_revision = '455980e4b944'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onde_remar', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('onde_remar', sa.Column('telefone', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onde_remar', 'telefone')
    op.drop_column('onde_remar', 'endereco')
    ### end Alembic commands ###
