"""empty message

Revision ID: b8c6a3167d5d
Revises: 6e469162ab8f
Create Date: 2016-03-21 21:36:21.670869

"""

# revision identifiers, used by Alembic.
revision = 'b8c6a3167d5d'
down_revision = '6e469162ab8f'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('url_pagamento', sa.String(), nullable=True))
    op.add_column('cursos', sa.Column('valor', sa.Integer(), nullable=True))
    op.add_column('eventos', sa.Column('url_pagamento_cursos', sa.String(), nullable=True))
    op.add_column('eventos', sa.Column('url_pagamento_provas', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'url_pagamento_provas')
    op.drop_column('eventos', 'url_pagamento_cursos')
    op.drop_column('cursos', 'valor')
    op.drop_column('cursos', 'url_pagamento')
    ### end Alembic commands ###
