"""empty message

Revision ID: bb2a34ab0c01
Revises: e3e443c983f7
Create Date: 2016-09-17 18:08:33.672654

"""

# revision identifiers, used by Alembic.
revision = 'bb2a34ab0c01'
down_revision = 'e3e443c983f7'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('thumbnail_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias', 'thumbnail_url')
    ### end Alembic commands ###
