"""empty message

Revision ID: c41189ad3350
Revises: 0fd7e4abed38
Create Date: 2016-09-17 23:32:35.481098

"""

# revision identifiers, used by Alembic.
revision = 'c41189ad3350'
down_revision = '0fd7e4abed38'

from alembic import op
import app
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('imagens_urls', sa.Text(), nullable=True))
    op.drop_column('noticias', 'imagens_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('imagens_url', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('noticias', 'imagens_urls')
    ### end Alembic commands ###
