"""empty message

Revision ID: c822a105fbfb
Revises: 8d8b79d14d9f
Create Date: 2016-04-02 15:08:37.782236

"""

# revision identifiers, used by Alembic.
revision = 'c822a105fbfb'
down_revision = '8d8b79d14d9f'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados', sa.Column('atleta_nome', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultados', 'atleta_nome')
    ### end Alembic commands ###
