"""empty message

Revision ID: ca31a5843986
Revises: 4ac788ccf1af
Create Date: 2016-09-17 14:20:04.428239

"""

# revision identifiers, used by Alembic.
revision = 'ca31a5843986'
down_revision = '4ac788ccf1af'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('corpo', sa.Text(), nullable=False))
    op.drop_column('noticias', 'corpo_novo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('corpo_novo', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('noticias', 'corpo')
    ### end Alembic commands ###
