"""empty message

Revision ID: df7c9e698ce1
Revises: f8b110875ac9
Create Date: 2016-03-03 20:04:20.115273

"""

# revision identifiers, used by Alembic.
revision = 'df7c9e698ce1'
down_revision = 'f8b110875ac9'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crossfit')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crossfit',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    ### end Alembic commands ###
