"""empty message

Revision ID: e3e443c983f7
Revises: 906c5a1888e0
Create Date: 2016-09-17 14:30:43.200201

"""

# revision identifiers, used by Alembic.
revision = 'e3e443c983f7'
down_revision = '906c5a1888e0'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'noticias', ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'noticias', type_='unique')
    ### end Alembic commands ###
