"""empty message

Revision ID: e554f67657d1
Revises: 06517eada72e
Create Date: 2016-09-17 12:58:13.739899

"""

# revision identifiers, used by Alembic.
revision = 'e554f67657d1'
down_revision = '06517eada72e'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'newsletters', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newsletters', type_='unique')
    ### end Alembic commands ###
