"""empty message

Revision ID: f8b110875ac9
Revises: 6506ed199f9b
Create Date: 2016-03-03 11:18:01.414991

"""

# revision identifiers, used by Alembic.
revision = 'f8b110875ac9'
down_revision = '6506ed199f9b'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provas', sa.Column('ordem', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provas', 'ordem')
    ### end Alembic commands ###
