"""empty message

Revision ID: fd6e26bc74e3
Revises: None
Create Date: 2016-03-01 13:31:22.475600

"""

# revision identifiers, used by Alembic.
revision = 'fd6e26bc74e3'
down_revision = None

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(length=2), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=10), nullable=True),
    sa.Column('celular', sa.String(length=11), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('subtitulo', sa.String(), nullable=True),
    sa.Column('imagem_lista', sa.String(), nullable=True),
    sa.Column('imagem_destaque', sa.String(), nullable=True),
    sa.Column('imagem_logo', sa.String(), nullable=True),
    sa.Column('imagem_propaganda', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('fundo', sa.String(), nullable=True),
    sa.Column('href_link', sa.String(), nullable=True),
    sa.Column('nome_link', sa.String(), nullable=True),
    sa.Column('em_destaque', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distancia', sa.Integer(), nullable=True),
    sa.Column('sexo', app.database.SexoTipo(), nullable=True),
    sa.Column('tipo', app.database.ProvaTipo(), nullable=True),
    sa.Column('sub_categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_categoria_id'], ['sub_categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=True),
    sa.Column('afiliacao', sa.String(length=120), nullable=True),
    sa.Column('nome_time', sa.String(length=120), nullable=True),
    sa.Column('prova_id', sa.Integer(), nullable=True),
    sa.Column('pedido_numero', sa.String(length=10), nullable=True),
    sa.Column('comprovante_pagamento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricoes')
    op.drop_table('provas')
    op.drop_table('sub_categorias')
    op.drop_table('produtos')
    op.drop_table('eventos')
    op.drop_table('categorias')
    op.drop_table('atletas')
    ### end Alembic commands ###
